name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    env:
      PLACES_API_KEY: ${{ secrets.PLACES_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install && npm install -g @lhci/cli@0.6.x
      - run: npm run build
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
